pull_request_rules:
  - name: Dependabot automatic merges
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build (10.x)
      - check-success=build (12.x)
      - "#check-failure=0"
    actions:
      merge:
        method: squash
