import { InputConfiguration } from './InputConfiguration';

export type TimeSpecification = {
    fromNow?: 'this' | 'last' | 'next',
    unit?: 'hour' | 'day' | 'week' | 'month',
    dateTime?: Date | string,
    offset?: string
};

export class AppConfigurationOptions {
    minimumLoggableTimeSlotInMinutes: number;
    timeZone: string;
    timePeriod: {
        begin: TimeSpecification,
        end: TimeSpecification;
        // generated by internal configuration post-processing
        startDateTime: Date;
        endDateTime: Date;
    };
}

export class AppConfiguration {
    options: AppConfigurationOptions;
    inputs: InputConfiguration[];
}
